version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "si-account-info"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19040ofskou93"
s3_prefix = "si-account-info"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
